### PR TITLE
implement episode mutable info map and fix the bug when fix an unfinished file.

### PR DESCRIPTION
**Pull request by hongBry**
#### fix the bug when fix an unfinished file. #2

### CODE REVIEW

**Comment by sometao** [comment]
TemporaryBuffer can only be updated by refreshing all the data?
If I only want to add just one kv pair, the hole temp file will be updated?
What if the temp file a bit big ( eg, 10+M ) or kv pair update fast?

**Comment by hongBry** [comment]
yes, TemporaryBuffer will be updated by refreshing all the data. 
Indeed it will affect the performance of update episode mutable Info and can‘t be recovered when write process is interrupted.

**Improvement Proposal:**
use the "event" mechanism to persistence store the update events of mutable info and box indexes. When fix, episode mutable info can be recover through trace back all events.

**Comment by sometao** [comment]
Good job.  Go ahead.

**Comment by hongBry** [comment]
@sometao 
Already implement the "event" mechanism to persistence store the update events of mutable info. [https://github.com/seekloud/ESSF/pull/4](url)

**Pull request closed without merging**
